language: node_js

node_js:
  - "node"

branches:
  only:
  - master

script:
  - yarn test
  - xvfb-run yarn e2e
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    branch: master
